# Site wide configuration
url: http://localhost:4000

owner:
  google:
    ad-client: ""
    ad-slot: ""
    analytics: ""
    verify: ""
  bing:
    verify: ""
  alexa:
    verify: ""
  yandex:
    verify: ""
disqus-shortname: akasralikar-dev


# Plugin: jekyll-assets

assets:
  cache: false
